version: '3'

services:
  web:
    container_name: wiki
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: jekyll serve
    ports:
      - "4000:4000"

